name: "Build Mediquince IOS App"

on:
  push:
    tags: v2.*

jobs:

  build:
    name: Build and Test IOS App
    runs-on: macos-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Test
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
      - name: Install Node.js, NPM
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install Cordova
        run: npm install -g cordova
        
      - name: Add platform
        run: cordova platform add android
      
      - name: Build app
        working-directory: ./
        run: cordova build ios
