name: "Build Mediquince IOS App"

on:
  push:
    tags: v0.*

jobs:

  build:
    name: Build and Test IOS App
    runs-on: macos-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      
      - name: Test
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
      
      - name: Install Node.js, NPM
        uses: actions/setup-node@v1
        with:
          node-version: 12
        
      - name: Install Cordova, Cordova-res, Ionic CLI
        run: npm install -g cordova cordova-res @ionic/cli
        
      - name: Add platform
        run: ionic cordova platform add ios
      
      - name: satisfying Dependeny
        run: npm i @angular-devkit/architect
      
      - name: Build app
        uses: yukiarrr/ios-build-action@v1.4.0
        with:
          project-path: /Users/runner/work/ios-buidtest-ionic5/ios-buidtest-ionic5/platforms/ios/ios-test.xcodeproj
          p12-base64: ${{ secrets.P12_BASE64 }}
          mobileprovision-base64: ${{ secrets.MOBILEPROVISION_BASE64 }}
          code-signing-identity: ${{ secrets.CODE_SIGNING_IDENTITY }}
          team-id: ${{ secrets.TEAM_ID }}
          export-method: "development"
          workspace-path: /Users/runner/work/ios-buidtest-ionic5/ios-buidtest-ionic5/platforms/ios/ios-test.xcworkspace
          output-path: /Users/runner/work/ios-buidtest-ionic5/ios-buidtest-ionic5/platforms/ios/outputs/ios_build_test.ipa

      - name: check build folder
        working-directory: /Users/runner/work/ios-buidtest-ionic5/ios-buidtest-ionic5/platforms
        run: |
          tar -czvf ios.tar.gz -C ./ios .
          ls -a
        
      - name: Upload to Diawi        
        uses: rnkdsh/action-upload-diawi@v1.2.1
        with:
          token: tdQcfLBx7oD1tUCQDdHA5jYT6BToTJNIHEdkAO0t1T
          file: /Users/runner/work/ios-buidtest-ionic5/ios-buidtest-ionic5/platforms/ios/outputs/ios_build_test.ipa
