name: "Build Aiimtech Test IOS App"

on:
  push:
    tags: v0.*

jobs:

  build:
    name: Build and Test IOS App
    runs-on: macos-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      
      - name: Test
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
      
      - name: Install Node.js, NPM
        uses: actions/setup-node@v1
        with:
          node-version: 12
        
      - name: Install Cordova, Cordova-res, Ionic CLI
        run: npm install -g cordova cordova-res @ionic/cli
        
      - name: Add platform
        run: ionic cordova platform add ios
      
      - name: satisfying Dependeny
        run: npm i @angular-devkit/architect

      - name: Set environment variables from project settings
        run: 
          shell: bash
          working-directory: scripts
          exec .github/scripts/set-env-from-xcodeproj.sh

      - name: Import signing certificate
        env:
          SIGNING_CERTIFICATE_P12_DATA: ${{ secrets.SIGNING_CERTIFICATE_P12_DATA }}
          SIGNING_CERTIFICATE_PASSWORD: ${{ secrets.SIGNING_CERTIFICATE_PASSWORD }}
        run: |
          exec .github/scripts/import-certificate.sh

      - name: Import provisioning profile
        env:
          PROVISIONING_PROFILE_DATA: ${{ secrets.PROVISIONING_PROFILE_DATA }}
        run: |
          exec .github/scripts/import-profile.sh
  
      - name: Build app
        run: |
          fastlane run build_app

      - name: Upload to Diawi        
        uses: rnkdsh/action-upload-diawi@v1.2.1
        with:
          token: tdQcfLBx7oD1tUCQDdHA5jYT6BToTJNIHEdkAO0t1T
          file: ${{ env.PRODUCT_NAME }}.ipa
