name: "Build Aiimtech Test IOS App"

on:
  push:
    tags: v0.*

jobs:

  build:
    name: Build and Test IOS App
    runs-on: macos-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      
      - name: Test
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
      
      - name: Install Node.js, NPM
        uses: actions/setup-node@v2
        with:
          node-version: 14
        
      - name: Install Cordova, Cordova-res, Ionic CLI
        run: |
          node -v
          npm install -g cordova cordova-res @ionic/cli
        
      - name: Add platform
        run: ionic cordova platform add ios
      
      - name: Import signing certificate
        env:
          PROJECT_PATH: /Users/runner/work/ios-buidtest-ionic5/ios-buidtest-ionic5/platforms/ios/
          SIGNING_CERTIFICATE_P12_DATA: ${{ secrets.SIGNING_CERTIFICATE_P12_DATA }}
          SIGNING_CERTIFICATE_PASSWORD: ${{ secrets.SIGNING_CERTIFICATE_PASSWORD }}
        run: |
          exec .github/scripts/import-certificate.sh
          echo ${{ env.PROJECT_PATH }}

      - name: Import provisioning profile
        env:
          PROVISIONING_PROFILE_DATA: ${{ secrets.PROVISIONING_PROFILE_DATA }}
        run: |
          exec .github/scripts/import-profile.sh
        
      - name: Copy Scripts
        run: cp .github/scripts/set-env-from-xcodeproj.sh /Users/runner/work/ios-buidtest-ionic5/ios-buidtest-ionic5/platforms/ios/

      - name: Set environment variables from project settings
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        working-directory: /Users/runner/work/ios-buidtest-ionic5/ios-buidtest-ionic5/platforms/ios/
        run: |
          exec ./set-env-from-xcodeproj.sh
  
      - name: Build app
        run: |
          fastlane run build_app

      - name: Upload to Diawi        
        uses: rnkdsh/action-upload-diawi@v1.2.1
        with:
          token: tdQcfLBx7oD1tUCQDdHA5jYT6BToTJNIHEdkAO0t1T
          file: ${{ env.PRODUCT_NAME }}.ipa