name: "Build Aiimtech Test IOS App"

on:
  push:
    tags: v0.*

jobs:
  build:
    name: Build and Test IOS App
    runs-on: macos-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      
      - name: Test
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
      
      - name: Install Node.js, NPM
        uses: actions/setup-node@v2
        with:
          node-version: 14
        
      - name: Install Cordova, Cordova-res, Ionic CLI
        run: |
          node -v
          npm install -g cordova cordova-res @ionic/cli
        
      - name: Add platform
        run: ionic cordova platform add ios

      - name: Build app
        uses: yukiarrr/ios-build-action@v1.4.0
        with:
          project-path: /Users/runner/work/ios-buidtest-ionic5/ios-buidtest-ionic5/platforms/ios/ios-test.xcodeproj
          p12-base64: ${{ secrets.SIGNING_CERTIFICATE_P12_DATA }}
          mobileprovision-base64: ${{ secrets.PROVISIONING_PROFILE_DATA }}
          code-signing-identity: ${{ secrets.CODE_SIGNING_IDENTITY }}
          team-id: ${{ secrets.TEAM_ID }}
          configuration: "Debug"
          certificate-password: ${{ secrets.SIGNING_CERTIFICATE_PASSWORD }}
          export-method: "development"
          workspace-path: /Users/runner/work/ios-buidtest-ionic5/ios-buidtest-ionic5/platforms/ios/ios-test.xcworkspace
          output-path: /Users/runner/work/ios-buidtest-ionic5/ios-buidtest-ionic5/platforms/ios/outputs/ios_build_test.ipa

      - name: Upload to Diawi        
        uses: rnkdsh/action-upload-diawi@v1.2.1
        with:
          token: "58MNqgV7oTpX4tcOWHcqg9fc40zhRqs6OKvncMzQUm"
          file: /Users/runner/work/ios-buidtest-ionic5/ios-buidtest-ionic5/platforms/ios/outputs/ios_build_test.ipa