name: "Build Aiimtech Test IOS App"

on:
  push:
    tags: v0.*

jobs:
  build:
    name: Build and Test IOS App
    runs-on: macos-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set env
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo "PROJECT_PATH=${GITHUB_WORKSPACE}/platforms/ios/" >> $GITHUB_ENV

      - name: Install Cordova, Cordova-res, Ionic CLI
        run: npm install -g cordova cordova-res @ionic/cli

      - name: Add platform
        run: ionic cordova platform add ios

      - name: Move to ios folder and install pod
        working-directory: /Users/runner/work/ios-buidtest-ionic5/ios-buidtest-ionic5/platforms/ios
        run: pod install

      - name: Build app
        uses: yukiarrr/ios-build-action@v1.4.0
        with:
          project-path: ${{ env.PROJECT_PATH }}${{ secrets.PRODUCT_NAME }}.xcodeproj
          workspace-path: ${{ env.PROJECT_PATH }}${{ secrets.PRODUCT_NAME }}.xcworkspace
          output-path: ${{ env.PROJECT_PATH }}outputs/${{ secrets.PRODUCT_NAME }}-${{env.RELEASE_VERSION}}.ipa
          scheme: ${{ secrets.PRODUCT_NAME }}
          team-id: ${{ secrets.TEAM_ID }}
          code-signing-identity: ${{ secrets.CODE_SIGNING_IDENTITY }}
          p12-base64: ${{ secrets.SIGNING_CERTIFICATE_P12_DATA }}
          certificate-password: ${{ secrets.SIGNING_CERTIFICATE_PASSWORD }}
          mobileprovision-base64: ${{ secrets.PROVISIONING_PROFILE_DATA }}
          configuration: "Debug"
          export-method: "development"